= Flatpak warning in VSCode
//changed to adoc from txt

* link:https://www.flathub.org[]

[WARNING]
====
You are running an unofficial Flatpak version of Visual Studio Code !!!
====

Please open issues under: link:https://github.com/flathub/com.visualstudio.code/issues[]


This version is running inside a container and is therefore not able
to access SDKs on your host system!

To execute commands on the host system, run inside the sandbox:

[,console]
----
$ host-spawn <COMMAND>
----
  
To make the Integrated Terminal automatically use the host system's shell,
you can add this to your profile settings:

[,profile]
----
{
  "terminal.integrated.defaultProfile.linux": "bash",
  "terminal.integrated.profiles.linux": {
    "bash": {
      "path": "host-spawn",
      "args": ["bash"]
    }
  }
}
----

This Flatpak provides a standard development environment (gcc, python, etc).
To see what's available:

[,console]
====
$ flatpak run --command=sh com.visualstudio.code
$ ls /usr/bin (shared runtime)
$ ls /app/bin (bundled with this flatpak)
====

To get support for additional languages or tools within the Flatpak, you have to install SDK extensions, e.g.

[,console]
====
$ flatpak install flathub org.freedesktop.Sdk.Extension.dotnet
$ flatpak install flathub org.freedesktop.Sdk.Extension.golang
$ FLATPAK_ENABLE_SDK_EXT=dotnet,golang flatpak run com.visualstudio.code
====

Similarly for shells and other tools:

[,console]
====
$ flatpak install com.visualstudio.code.tool.fish
$ flatpak install com.visualstudio.code.tool.podman
====

You can use

[,console]
====
$ flatpak search <TEXT>
====

to find others.

Also see link:https://code.visualstudio.com/docs/terminal/shell-integration[]
